# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
data_file = "city_data2.csv"
data_file_df = pd.read_csv(data_file)
data_file_df.head()
#checkpoint

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,victoria,22.2855,114.1577,75.00,87,100,1.01,HK,1619450373
1,1,cidreira,-30.1811,-50.2056,67.98,63,66,13.58,BR,1619450441
2,2,ust-kuyga,70.0167,135.6000,27.34,98,100,1.70,RU,1619450441
3,3,maanshan,31.6957,118.4983,64.40,100,90,6.71,CN,1619450441
4,4,manggar,-2.8833,108.2667,82.47,71,25,5.95,ID,1619450442

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
#config gmaps
gmaps.configure(api_key=g_key)

In [29]:
locations = data_file_df[['Lat', 'Lng']]
weight = data_file_df['Humidity']
fig = gmaps.figure(map_type='SATELLITE')
fig.add_layer(gmaps.heatmap_layer(locations, weights=weight))
fig

TraitError: locations is not a valid location. Locations must have length 2.

* Narrow down the DataFrame to find your ideal weather condition. For example:

  * A max temperature lower than 80 degrees but higher than 70.

  * Wind speed less than 10 mph.

  * Zero cloudiness.

  * Drop any rows that don't contain all three conditions. You want to be sure the weather is ideal.

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [14]:
clean_data = data_file_df
clean_data = clean_data.dropna()
clean_data = clean_data.loc[(clean_data['Max Temp'] > 70) & (clean_data['Max Temp'] < 90) & (clean_data['Cloudiness'] == 0) & (clean_data['Wind Speed'] < 10)]
clean_data.head()

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
20,20,east london,-33.0153,27.9116,73.40,73,0,6.91,ZA,1619450447
33,33,nurobod,40.9056,69.8023,77.00,25,0,6.91,UZ,1619450451
57,57,awjilah,29.1081,21.2869,81.79,19,0,7.72,LY,1619450460
90,90,maxixe,-23.8597,35.3472,75.76,74,0,8.16,MZ,1619450471
100,100,mangit,40.5971,70.9607,71.60,35,0,4.61,UZ,1619450475

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [15]:
hotel_df = clean_data
hotel_df['Hotel Name'] = ""
hotel_df.head()
#checkpoint

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
20,20,east london,-33.0153,27.9116,73.40,73,0,6.91,ZA,1619450447,
33,33,nurobod,40.9056,69.8023,77.00,25,0,6.91,UZ,1619450451,
57,57,awjilah,29.1081,21.2869,81.79,19,0,7.72,LY,1619450460,
90,90,maxixe,-23.8597,35.3472,75.76,74,0,8.16,MZ,1619450471,
100,100,mangit,40.5971,70.9607,71.60,35,0,4.61,UZ,1619450475,

In [26]:
base_url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json'
from pprint import pprint
#create params for radius <5000, hotel, dont forget g_key
#params = {'radius':5000, 'types': 'hotel', 'key': g_key, 'location': ['Lat'],['Lng']} cant get location to work...found solution online seems to work... recreated variables for lng/lat
params = {'radius':5000, 'types': 'hotel', 'key': g_key}

for index, row in hotel_df.iterrows():
    lat = row['Lat']
    lng = row['Lng']
    params['location'] = f'{lat},{lng}'
    response = requests.get(base_url, params=params).json()
    results = response['results']
    
    try:
        #print(f"Closest {} restaurant is {results[0]['name']}.")
        
        hotel_df.loc[index, 'Hotel Name'] = results[0]['name']
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
hotel_df.head()

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
20,20,east london,-33.0153,27.9116,73.40,73,0,6.91,ZA,1619450447,East London
33,33,nurobod,40.9056,69.8023,77.00,25,0,6.91,UZ,1619450451,Nurabad
57,57,awjilah,29.1081,21.2869,81.79,19,0,7.72,LY,1619450460,Awjilah
90,90,maxixe,-23.8597,35.3472,75.76,74,0,8.16,MZ,1619450471,Maxixe
100,100,mangit,40.5971,70.9607,71.60,35,0,4.61,UZ,1619450475,Kokand

In [33]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [34]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))